1) без EntTrans
exception:
javax.servlet.ServletException: javax.persistence.TransactionRequiredException

root cause:
javax.persistence.TransactionRequiredException

2) c EntTrans

javax.servlet.ServletException: java.lang.IllegalStateException: Exception Description: Cannot use an EntityTransaction while using JTA.